### PR TITLE
Remove 3.0 documentation

### LINKED ISSUE #42: Remove v3 docs
When fixing #28 - found that there were two copies of the file under v2.6 and v3.0. 

I only fixed the v2.6 copy, are the 3.0 docs in this repo now redundant, and can we remove them?

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #42, as I had the repo open, and am 80% sure this will be the way to go! Please close if not. :smile:

### CODE REVIEW

**Comment by rprouse** [comment]
Seems right to me. Any reason to keep this @charliepoole?

**Comment by CharliePoole** [comment]
I removed them from the web site but kept them here for a final check, which is no doubt overdue. :-)

I'll take a look through to make sure everything we need was transferred to the wiki.

**Comment by rprouse** [comment]
This looks fine. @CharliePoole do you want to keep this PR open to do a comparison against the Wiki?

**Comment by CharliePoole** [comment]
Well, if it means that much to you... :smile:

**Pull request merged**
