### PR TITLE
Updated for the 3.5 framework release

### PR DESCRIPTION
**Pull request by rprouse**
Pushing these changes to the website for the 3.5 framework release.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
http://nunit.org/index.php?p=documentation

This page also has a version number, although I imagine it can be changed to 3.x and future-proofed. 👍 Otherwise, looks good. 😄

**Comment by rprouse** [comment]
@ChrisMaddock good catch. I updated the version to 3.x in this branch and pushed it to the website.

**Comment by CharliePoole** [comment]
I'm seeing the website without any css formatting! I'll try again from home, in case it's to do with my network connection.

I thought we had agreed to use "NUnit 3" rather than 3.x when talking about NUnit 3 generically. I think 3.x is fine for email discussions, etc., when we mean "the set of releases with major version 3" but isn't really a user-friendly description for use in the website.

**Comment by rprouse** [comment]
I can change it to 3, I agree it reads better.

**Comment by rprouse** [comment]
I think the CSS is your connection. It is coming up fine here and I only uploaded individual files.

**Comment by CharliePoole** [comment]
You're right. The page displays fine now that I'm home.

**Pull request merged**
