### PR TITLE
nunit.xamarin 3.6.1 release

### PR DESCRIPTION
**Pull request by ChrisMaddock**
**NOT READY TO MERGE** - This will be for @rprouse to merge, after reviewing and releasing https://github.com/nunit/nunit.xamarin/pull/90 (which I hope to complete the work for tonight!)

-------------------

I know historically we've only put the 'core products' on the download page - but I thought it might give the Xamarin runners a little more exposure, adding them here. What do people think - @rprouse @nunit/core-team?

### CODE REVIEW

**Comment by rprouse** [comment]
I am okay with including this in the downloads. The Xamarin runners are getting more traction recently. @CharliePoole?

**Comment by CharliePoole** [comment]
I still think this is experimental. Do you guys? Maybe a separate section?

**Comment by rprouse** [comment]
I would be fine with a separate section.

**Comment by ChrisMaddock** [comment]
Happy to put it in a separate section.

How should we title it? I'm not sure about 'experimental' - is there a path towards making it un-experimental? I've considered this ready for use, have I been mistaken?

**Comment by CharliePoole** [comment]
Perhaps it's "Development". 😄 

One of the things I would like to see the new core team do is to decide on "categories" for projects. I see this as very important because being a "core" or "production" product (whatever we call it) means we promise to users that we will keep supporting it in the future. Compare that to a "contributed" project like the junit transform - I don't think we are under any obligation to support it if the contributor should disappear. The teamcity extension is similar, although I'm sure JetBrains isn't going to disappear.

Anyway, without discussing the merits of any particular cases, I hope that shows why I think it's important to know whether a project is "core" or "developmental". We have to agree on terms eventually, of course, but to me "developmental" means it's on the way to "core", while "experimental" means we might cancel the whole project at any point.

Obviously, none of this is of any use unless users know about the distinctions.

Given that it's such a big deal, maybe you should just merge what you have and we can discuss it further in the context of #55. @rprouse?

**Comment by rprouse** [comment]
I'm okay with just merging for now and making the larger decision in #55.

**Pull request merged**
